/**
 * Auto-generated registry of beta endpoints.
 * DO NOT EDIT — regenerated by scripts/utils/generate-beta-endpoints.cjs
 *
 * Maps URL paths to qualified method names for runtime warnings.
 */
export const BETA_ENDPOINTS: Record<string, string> = {
  '/detection/v2/request-evaluations': 'Runtime.evaluateRequest',
  '/detection/v2/response-evaluations': 'Runtime.evaluateResponse',
  '/evaluations/v1/red-team': 'RedTeam.create',
};
