/**
 * Auto-generated registry of beta endpoints.
 * DO NOT EDIT — regenerated by scripts/utils/generate-beta-endpoints.cjs
 *
 * Each entry is a path pattern: an array of segments where a string is a literal
 * match and `null` is a wildcard matching any single path-parameter segment.
 * Used by checkBetaEndpoint to emit runtime warnings for beta endpoints.
 */
export const BETA_ENDPOINTS: ReadonlyArray<{ segments: ReadonlyArray<string | null>; method: string }> = [
  { segments: ['detection', 'v2', 'interaction-evaluations'], method: 'Runtime.evaluateInteraction' },
  { segments: ['detection', 'v2', 'request-evaluations'], method: 'Runtime.evaluateRequest' },
  { segments: ['detection', 'v2', 'response-evaluations'], method: 'Runtime.evaluateResponse' },
  { segments: ['evaluations', 'v1', 'jobs', null, 'termination'], method: 'RedTeam.terminate' },
  { segments: ['evaluations', 'v1', 'red-team'], method: 'RedTeam.create' },
  { segments: ['evaluations', 'v1', 'red-team', null], method: 'RedTeam.retrieveEvaluationResults' },
  { segments: ['evaluations', 'v1', 'red-team', null, 'next-action'], method: 'RedTeam.retrieveNextAction' },
  { segments: ['evaluations', 'v1', 'red-team', null, 'status'], method: 'RedTeam.retrieveStatus' },
  {
    segments: ['evaluations', 'v1', 'red-team', null, 'target-response'],
    method: 'RedTeam.submitTargetResponse',
  },
];
