name: Node CI

on:
    pull_request: {}
    push:
        branches:
            - main

permissions:
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [18.x, 20.x]
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
              with:
                egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install modules
              run: npm install

            - name: Cache node modules
              uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  # This uses the same name as the build-action so we can share the caches.
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Lint code
              run: npm run lint
            - name: Login to Quay
              uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
              with:
                registry: quay.io
                username: ${{ vars.QUAY_USERNAME }}
                password: ${{ secrets.QUAY_TOKEN }}
            - name: Start Enterprise Model Scanner
              run: docker compose -f integration-tests/enterprise-modscan/docker-compose.yaml up -d
            - name: Run tests
              run: npm run test
              env:
                  HL_CLIENT_ID: ${{ secrets.HL_CLIENT_ID}}
                  HL_CLIENT_SECRET: ${{ secrets.HL_CLIENT_SECRET}}
            - name: Stop Enterprise Model Scanner
              if: always()
              run: docker compose -f integration-tests/enterprise-modscan/docker-compose.yaml down
